### ISSUE TITLE
Change .gitmodules to use https instead of git

### ISSUE THREAD

**Issue by piperoc** [shuai132/asio_net#1]
When I try cloning this repo, the submodules will fail due to the git SSH settings. 

```shell
 git clone --recurse-submodules https://github.com/shuai132/asio_net.git
Cloning into 'asio_net'...
remote: Enumerating objects: 1004, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (42/42), done.
Receiving objects:  96% (964/1004)sed 58 (delta 41), pack-reused 921
Receiving objects: 100% (1004/1004), 139.83 KiB | 11.65 MiB/s, done.
Resolving deltas: 100% (689/689), done.
Submodule 'include/asio_net/rpc_core' (git@github.com:shuai132/rpc_core.git) registered for path 'include/asio_net/rpc_core'
Cloning into 'C:/Users/me/Downloads/asio_net/include/asio_net/rpc_core'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:shuai132/rpc_core.git' into submodule path 'C:/Users/me/Downloads/asio_net/include/asio_net/rpc_core' failed
Failed to clone 'include/asio_net/rpc_core'. Retry scheduled
Cloning into 'C:/Users/me/Downloads/asio_net/include/asio_net/rpc_core'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:shuai132/rpc_core.git' into submodule path 'C:/Users/me/Downloads/asio_net/include/asio_net/rpc_core' failed
Failed to clone 'include/asio_net/rpc_core' a second time, aborting
```

this is due to the fact that you added the submodule using the git protocol.

```
[submodule "include/asio_net/rpc_core"]
	path = include/asio_net/rpc_core
	url = git@github.com:shuai132/rpc_core.git
```

In order to fix this I forked the repo (https://github.com/piperoc/asio_net) and changed the `.gitmodules` file to use the https url instead:

```
[submodule "include/asio_net/rpc_core"]
	path = include/asio_net/rpc_core
	url = https://github.com/shuai132/rpc_core.git
```

This way everything works. 

I needed to do this because in my project I manage all the dependencies with the CMake's `FetchContent` method.

I would rather use your repo than keep syncing my fork. 
Hopefully this will help others running into this issue.

Thanks

**Comment by shuai132** [comment]
You should config ssh settings in your github account.
Then, you can download success I guess.

BTW:
submodule should use `ssh`, becasue `https` will be complained by github (github will not support https in submodule soon).
I use https first, and change to ssh after got the notice log.

**Comment by piperoc** [comment]
Thank you , that makes sense.
The issue I had was that I was using `FetchContent_Declare` to connect to asio_net, like so:

```cmake
...
FetchContent_Declare(
        asio_net
        GIT_REPOSITORY https://github.com/shuai132/asio_net.git
        GIT_TAG v2.0.1
    )
...
```

which would start downloading the repo, but eventually got stuck without saying why. I then figured there was a submodule and noticed the `git-ssh` url. CMake did not like to mix it.

So, I changed that section to use `git-ssh`:



Therefore, the solution is to use `git-ssh` all the way (like @shuai132 said)
```cmake
...
FetchContent_Declare(
        asio_net
        GIT_REPOSITORY git@github.com:shuai132/asio_net.git
        GIT_TAG v2.0.1
    )
...
```

_**This will not work until you have the SSH fingerprint recorded in your computer**_. To do that, I cloned the repo once using the command line

```shell
git clone --recurse-submodules git@github.com:shuai132/asio_net.git
Cloning into 'asio_net'...
The authenticity of host 'github.com (140.82.112.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.112.3' (ECDSA) to the list of known hosts.
```

After that, all the `FetchContent` stuff will work.
Not as easy as https, but that's how it's going to be. I figured I described this in case someone else runs into this issue.

Thank you again for replying.
