### ISSUE TITLE
"multiple definition of" errors when building from CMake

### ISSUE THREAD

**Issue by piperoc** [shuai132/asio_net#2]
I don't think this is a CMake related issue, but I'm writing a program that uses CMake so.

When I build a simple server test, I get a bunch of `multiple definition` errors, like

```shell
In function `void asio_net::detail::tcp_server_t<(asio_net::detail::socket_type)1>::do_accept<(asio_net::detail::socket_type)1>()':
[build] /home/me/build/_deps/asio_net-src/include/asio_net/detail/tcp_server_t.hpp:114: multiple definition of `void asio_net::detail::tcp_server_t<(asio_net::detail::socket_type)1>::do_accept<(asio_net::detail::socket_type)1>()'
```

This is probably due to the fact that the `do_accept()` declaration and definition are in the same header file (i.e. there is no .cpp file), which is a condition known to cause this kind of issues. Usually, people would get around by declaring the function as `inline`.

I'm not sure if there is any other way to tell the compiler to inline the functions...

Thanks for any suggestion

**Comment by piperoc** [comment]
As an update, I added the `inline` keyword to the offending functions and now my code builds and tests ok.

from this:
```cpp
...
template <>
void tcp_server_t<socket_type::domain>::do_accept<socket_type::domain>() {
  acceptor_.async_accept([this](const std::error_code& ec, socket socket) {
...
```

I simply changed it to 
```cpp
...
template <>
inline void tcp_server_t<socket_type::domain>::do_accept<socket_type::domain>() {
  acceptor_.async_accept([this](const std::error_code& ec, socket socket) {
...
```

However, I'm not sure this is a reliable long term strategy since it forces me to maintain my fork....

**Comment by shuai132** [comment]
Yes, we should use `inline` here. I will fix it.

**Comment by shuai132** [comment]
fixed: https://github.com/shuai132/asio_net/commit/6a6c86bcddf4fe8cfd22d674049b8978c746f28d

**Comment by piperoc** [comment]
I just tested and it builds ok. Thank you!

**Comment by piperoc** [comment]
I think this has been resolved
